spring:
  application:
    name: spending-tracker

  threads:
    virtual:
      enabled:

  mongodb:
    uri: mongodb://mongodb:27017/spending_tracker
  rabbitmq:
    host: rabbitmq

---
spring:
  config:
    activate:
      on-profile: default
  profiles:
    include: dev