spring:
  application:
    name: spending-tracker

  threads:
    virtual:
      enabled: true

  profiles:
    active: dev

  mongodb:
    uri: mongodb://mongodb:27017/spending_tracker
  rabbitmq:
    host: rabbitmq